-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module UniSwapGraph.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import UniSwapGraph.Scalar exposing (defaultCodecs)


type alias BigDecimal =
    UniSwapGraph.Scalar.BigDecimal


type alias BigInt =
    UniSwapGraph.Scalar.BigInt


type alias Bytes =
    UniSwapGraph.Scalar.Bytes


type alias Id =
    UniSwapGraph.Scalar.Id


codecs : UniSwapGraph.Scalar.Codecs BigDecimal BigInt Bytes Id
codecs =
    UniSwapGraph.Scalar.defineCodecs
        { codecBigDecimal = defaultCodecs.codecBigDecimal
        , codecBigInt = defaultCodecs.codecBigInt
        , codecBytes = defaultCodecs.codecBytes
        , codecId = defaultCodecs.codecId
        }
