-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module UniSwapGraph.Object.LiquidityPositionSnapshot exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import UniSwapGraph.InputObject
import UniSwapGraph.Interface
import UniSwapGraph.Object
import UniSwapGraph.Scalar
import UniSwapGraph.ScalarCodecs
import UniSwapGraph.Union


id : SelectionSet UniSwapGraph.ScalarCodecs.Id UniSwapGraph.Object.LiquidityPositionSnapshot
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecId |> .decoder)


liquidityPosition :
    SelectionSet decodesTo UniSwapGraph.Object.LiquidityPosition
    -> SelectionSet decodesTo UniSwapGraph.Object.LiquidityPositionSnapshot
liquidityPosition object_ =
    Object.selectionForCompositeField "liquidityPosition" [] object_ identity


timestamp : SelectionSet Int UniSwapGraph.Object.LiquidityPositionSnapshot
timestamp =
    Object.selectionForField "Int" "timestamp" [] Decode.int


block : SelectionSet Int UniSwapGraph.Object.LiquidityPositionSnapshot
block =
    Object.selectionForField "Int" "block" [] Decode.int


user :
    SelectionSet decodesTo UniSwapGraph.Object.User
    -> SelectionSet decodesTo UniSwapGraph.Object.LiquidityPositionSnapshot
user object_ =
    Object.selectionForCompositeField "user" [] object_ identity


pair :
    SelectionSet decodesTo UniSwapGraph.Object.Pair
    -> SelectionSet decodesTo UniSwapGraph.Object.LiquidityPositionSnapshot
pair object_ =
    Object.selectionForCompositeField "pair" [] object_ identity


token0PriceUSD : SelectionSet UniSwapGraph.ScalarCodecs.BigDecimal UniSwapGraph.Object.LiquidityPositionSnapshot
token0PriceUSD =
    Object.selectionForField "ScalarCodecs.BigDecimal" "token0PriceUSD" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


token1PriceUSD : SelectionSet UniSwapGraph.ScalarCodecs.BigDecimal UniSwapGraph.Object.LiquidityPositionSnapshot
token1PriceUSD =
    Object.selectionForField "ScalarCodecs.BigDecimal" "token1PriceUSD" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


reserve0 : SelectionSet UniSwapGraph.ScalarCodecs.BigDecimal UniSwapGraph.Object.LiquidityPositionSnapshot
reserve0 =
    Object.selectionForField "ScalarCodecs.BigDecimal" "reserve0" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


reserve1 : SelectionSet UniSwapGraph.ScalarCodecs.BigDecimal UniSwapGraph.Object.LiquidityPositionSnapshot
reserve1 =
    Object.selectionForField "ScalarCodecs.BigDecimal" "reserve1" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


reserveUSD : SelectionSet UniSwapGraph.ScalarCodecs.BigDecimal UniSwapGraph.Object.LiquidityPositionSnapshot
reserveUSD =
    Object.selectionForField "ScalarCodecs.BigDecimal" "reserveUSD" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


liquidityTokenTotalSupply : SelectionSet UniSwapGraph.ScalarCodecs.BigDecimal UniSwapGraph.Object.LiquidityPositionSnapshot
liquidityTokenTotalSupply =
    Object.selectionForField "ScalarCodecs.BigDecimal" "liquidityTokenTotalSupply" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


liquidityTokenBalance : SelectionSet UniSwapGraph.ScalarCodecs.BigDecimal UniSwapGraph.Object.LiquidityPositionSnapshot
liquidityTokenBalance =
    Object.selectionForField "ScalarCodecs.BigDecimal" "liquidityTokenBalance" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)
