-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module UniSwapGraph.Object.LiquidityPositionSnapshot exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs
import UniSwapGraph.InputObject
import UniSwapGraph.Interface
import UniSwapGraph.Object
import UniSwapGraph.Scalar
import UniSwapGraph.Union


id : SelectionSet ScalarCodecs.Id UniSwapGraph.Object.LiquidityPositionSnapshot
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecId |> .decoder)


liquidityPosition :
    SelectionSet decodesTo UniSwapGraph.Object.LiquidityPosition
    -> SelectionSet decodesTo UniSwapGraph.Object.LiquidityPositionSnapshot
liquidityPosition object_ =
    Object.selectionForCompositeField "liquidityPosition" [] object_ identity


timestamp : SelectionSet Int UniSwapGraph.Object.LiquidityPositionSnapshot
timestamp =
    Object.selectionForField "Int" "timestamp" [] Decode.int


block : SelectionSet Int UniSwapGraph.Object.LiquidityPositionSnapshot
block =
    Object.selectionForField "Int" "block" [] Decode.int


user :
    SelectionSet decodesTo UniSwapGraph.Object.User
    -> SelectionSet decodesTo UniSwapGraph.Object.LiquidityPositionSnapshot
user object_ =
    Object.selectionForCompositeField "user" [] object_ identity


pair :
    SelectionSet decodesTo UniSwapGraph.Object.Pair
    -> SelectionSet decodesTo UniSwapGraph.Object.LiquidityPositionSnapshot
pair object_ =
    Object.selectionForCompositeField "pair" [] object_ identity


token0PriceUSD : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.LiquidityPositionSnapshot
token0PriceUSD =
    Object.selectionForField "ScalarCodecs.BigDecimal" "token0PriceUSD" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


token1PriceUSD : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.LiquidityPositionSnapshot
token1PriceUSD =
    Object.selectionForField "ScalarCodecs.BigDecimal" "token1PriceUSD" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


reserve0 : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.LiquidityPositionSnapshot
reserve0 =
    Object.selectionForField "ScalarCodecs.BigDecimal" "reserve0" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


reserve1 : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.LiquidityPositionSnapshot
reserve1 =
    Object.selectionForField "ScalarCodecs.BigDecimal" "reserve1" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


reserveUSD : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.LiquidityPositionSnapshot
reserveUSD =
    Object.selectionForField "ScalarCodecs.BigDecimal" "reserveUSD" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


liquidityTokenTotalSupply : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.LiquidityPositionSnapshot
liquidityTokenTotalSupply =
    Object.selectionForField "ScalarCodecs.BigDecimal" "liquidityTokenTotalSupply" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


liquidityTokenBalance : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.LiquidityPositionSnapshot
liquidityTokenBalance =
    Object.selectionForField "ScalarCodecs.BigDecimal" "liquidityTokenBalance" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)
