-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module UniSwapGraph.Object.LiquidityPosition exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs
import UniSwapGraph.InputObject
import UniSwapGraph.Interface
import UniSwapGraph.Object
import UniSwapGraph.Scalar
import UniSwapGraph.Union


id : SelectionSet ScalarCodecs.Id UniSwapGraph.Object.LiquidityPosition
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecId |> .decoder)


user :
    SelectionSet decodesTo UniSwapGraph.Object.User
    -> SelectionSet decodesTo UniSwapGraph.Object.LiquidityPosition
user object_ =
    Object.selectionForCompositeField "user" [] object_ identity


pair :
    SelectionSet decodesTo UniSwapGraph.Object.Pair
    -> SelectionSet decodesTo UniSwapGraph.Object.LiquidityPosition
pair object_ =
    Object.selectionForCompositeField "pair" [] object_ identity


liquidityTokenBalance : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.LiquidityPosition
liquidityTokenBalance =
    Object.selectionForField "ScalarCodecs.BigDecimal" "liquidityTokenBalance" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)
