-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module UniSwapGraph.Object.Mint exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs
import UniSwapGraph.InputObject
import UniSwapGraph.Interface
import UniSwapGraph.Object
import UniSwapGraph.Scalar
import UniSwapGraph.Union


id : SelectionSet ScalarCodecs.Id UniSwapGraph.Object.Mint
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecId |> .decoder)


transaction :
    SelectionSet decodesTo UniSwapGraph.Object.Transaction
    -> SelectionSet decodesTo UniSwapGraph.Object.Mint
transaction object_ =
    Object.selectionForCompositeField "transaction" [] object_ identity


timestamp : SelectionSet ScalarCodecs.BigInt UniSwapGraph.Object.Mint
timestamp =
    Object.selectionForField "ScalarCodecs.BigInt" "timestamp" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigInt |> .decoder)


pair :
    SelectionSet decodesTo UniSwapGraph.Object.Pair
    -> SelectionSet decodesTo UniSwapGraph.Object.Mint
pair object_ =
    Object.selectionForCompositeField "pair" [] object_ identity


to : SelectionSet ScalarCodecs.Bytes UniSwapGraph.Object.Mint
to =
    Object.selectionForField "ScalarCodecs.Bytes" "to" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBytes |> .decoder)


liquidity : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.Mint
liquidity =
    Object.selectionForField "ScalarCodecs.BigDecimal" "liquidity" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


sender : SelectionSet (Maybe ScalarCodecs.Bytes) UniSwapGraph.Object.Mint
sender =
    Object.selectionForField "(Maybe ScalarCodecs.Bytes)" "sender" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBytes |> .decoder |> Decode.nullable)


amount0 : SelectionSet (Maybe ScalarCodecs.BigDecimal) UniSwapGraph.Object.Mint
amount0 =
    Object.selectionForField "(Maybe ScalarCodecs.BigDecimal)" "amount0" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder |> Decode.nullable)


amount1 : SelectionSet (Maybe ScalarCodecs.BigDecimal) UniSwapGraph.Object.Mint
amount1 =
    Object.selectionForField "(Maybe ScalarCodecs.BigDecimal)" "amount1" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder |> Decode.nullable)


logIndex : SelectionSet (Maybe ScalarCodecs.BigInt) UniSwapGraph.Object.Mint
logIndex =
    Object.selectionForField "(Maybe ScalarCodecs.BigInt)" "logIndex" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigInt |> .decoder |> Decode.nullable)


amountUSD : SelectionSet (Maybe ScalarCodecs.BigDecimal) UniSwapGraph.Object.Mint
amountUSD =
    Object.selectionForField "(Maybe ScalarCodecs.BigDecimal)" "amountUSD" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder |> Decode.nullable)


feeTo : SelectionSet (Maybe ScalarCodecs.Bytes) UniSwapGraph.Object.Mint
feeTo =
    Object.selectionForField "(Maybe ScalarCodecs.Bytes)" "feeTo" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBytes |> .decoder |> Decode.nullable)


feeLiquidity : SelectionSet (Maybe ScalarCodecs.BigDecimal) UniSwapGraph.Object.Mint
feeLiquidity =
    Object.selectionForField "(Maybe ScalarCodecs.BigDecimal)" "feeLiquidity" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder |> Decode.nullable)
