-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module UniSwapGraph.Object.PairDayData exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs
import UniSwapGraph.InputObject
import UniSwapGraph.Interface
import UniSwapGraph.Object
import UniSwapGraph.Scalar
import UniSwapGraph.Union


id : SelectionSet ScalarCodecs.Id UniSwapGraph.Object.PairDayData
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecId |> .decoder)


date : SelectionSet Int UniSwapGraph.Object.PairDayData
date =
    Object.selectionForField "Int" "date" [] Decode.int


pairAddress : SelectionSet ScalarCodecs.Bytes UniSwapGraph.Object.PairDayData
pairAddress =
    Object.selectionForField "ScalarCodecs.Bytes" "pairAddress" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBytes |> .decoder)


token0 :
    SelectionSet decodesTo UniSwapGraph.Object.Token
    -> SelectionSet decodesTo UniSwapGraph.Object.PairDayData
token0 object_ =
    Object.selectionForCompositeField "token0" [] object_ identity


token1 :
    SelectionSet decodesTo UniSwapGraph.Object.Token
    -> SelectionSet decodesTo UniSwapGraph.Object.PairDayData
token1 object_ =
    Object.selectionForCompositeField "token1" [] object_ identity


reserve0 : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.PairDayData
reserve0 =
    Object.selectionForField "ScalarCodecs.BigDecimal" "reserve0" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


reserve1 : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.PairDayData
reserve1 =
    Object.selectionForField "ScalarCodecs.BigDecimal" "reserve1" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


totalSupply : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.PairDayData
totalSupply =
    Object.selectionForField "ScalarCodecs.BigDecimal" "totalSupply" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


reserveUSD : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.PairDayData
reserveUSD =
    Object.selectionForField "ScalarCodecs.BigDecimal" "reserveUSD" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


dailyVolumeToken0 : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.PairDayData
dailyVolumeToken0 =
    Object.selectionForField "ScalarCodecs.BigDecimal" "dailyVolumeToken0" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


dailyVolumeToken1 : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.PairDayData
dailyVolumeToken1 =
    Object.selectionForField "ScalarCodecs.BigDecimal" "dailyVolumeToken1" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


dailyVolumeUSD : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.PairDayData
dailyVolumeUSD =
    Object.selectionForField "ScalarCodecs.BigDecimal" "dailyVolumeUSD" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


dailyTxns : SelectionSet ScalarCodecs.BigInt UniSwapGraph.Object.PairDayData
dailyTxns =
    Object.selectionForField "ScalarCodecs.BigInt" "dailyTxns" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigInt |> .decoder)
