-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module UniSwapGraph.Object.Swap exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import UniSwapGraph.InputObject
import UniSwapGraph.Interface
import UniSwapGraph.Object
import UniSwapGraph.Scalar
import UniSwapGraph.ScalarCodecs
import UniSwapGraph.Union


id : SelectionSet UniSwapGraph.ScalarCodecs.Id UniSwapGraph.Object.Swap
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecId |> .decoder)


transaction :
    SelectionSet decodesTo UniSwapGraph.Object.Transaction
    -> SelectionSet decodesTo UniSwapGraph.Object.Swap
transaction object_ =
    Object.selectionForCompositeField "transaction" [] object_ identity


timestamp : SelectionSet UniSwapGraph.ScalarCodecs.BigInt UniSwapGraph.Object.Swap
timestamp =
    Object.selectionForField "ScalarCodecs.BigInt" "timestamp" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigInt |> .decoder)


pair :
    SelectionSet decodesTo UniSwapGraph.Object.Pair
    -> SelectionSet decodesTo UniSwapGraph.Object.Swap
pair object_ =
    Object.selectionForCompositeField "pair" [] object_ identity


sender : SelectionSet UniSwapGraph.ScalarCodecs.Bytes UniSwapGraph.Object.Swap
sender =
    Object.selectionForField "ScalarCodecs.Bytes" "sender" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBytes |> .decoder)


amount0In : SelectionSet UniSwapGraph.ScalarCodecs.BigDecimal UniSwapGraph.Object.Swap
amount0In =
    Object.selectionForField "ScalarCodecs.BigDecimal" "amount0In" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


amount1In : SelectionSet UniSwapGraph.ScalarCodecs.BigDecimal UniSwapGraph.Object.Swap
amount1In =
    Object.selectionForField "ScalarCodecs.BigDecimal" "amount1In" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


amount0Out : SelectionSet UniSwapGraph.ScalarCodecs.BigDecimal UniSwapGraph.Object.Swap
amount0Out =
    Object.selectionForField "ScalarCodecs.BigDecimal" "amount0Out" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


amount1Out : SelectionSet UniSwapGraph.ScalarCodecs.BigDecimal UniSwapGraph.Object.Swap
amount1Out =
    Object.selectionForField "ScalarCodecs.BigDecimal" "amount1Out" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


to : SelectionSet UniSwapGraph.ScalarCodecs.Bytes UniSwapGraph.Object.Swap
to =
    Object.selectionForField "ScalarCodecs.Bytes" "to" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBytes |> .decoder)


logIndex : SelectionSet (Maybe UniSwapGraph.ScalarCodecs.BigInt) UniSwapGraph.Object.Swap
logIndex =
    Object.selectionForField "(Maybe ScalarCodecs.BigInt)" "logIndex" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigInt |> .decoder |> Decode.nullable)


amountUSD : SelectionSet UniSwapGraph.ScalarCodecs.BigDecimal UniSwapGraph.Object.Swap
amountUSD =
    Object.selectionForField "ScalarCodecs.BigDecimal" "amountUSD" [] (UniSwapGraph.ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)
