-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module UniSwapGraph.Object.Swap exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs
import UniSwapGraph.InputObject
import UniSwapGraph.Interface
import UniSwapGraph.Object
import UniSwapGraph.Scalar
import UniSwapGraph.Union


id : SelectionSet ScalarCodecs.Id UniSwapGraph.Object.Swap
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecId |> .decoder)


transaction :
    SelectionSet decodesTo UniSwapGraph.Object.Transaction
    -> SelectionSet decodesTo UniSwapGraph.Object.Swap
transaction object_ =
    Object.selectionForCompositeField "transaction" [] object_ identity


timestamp : SelectionSet ScalarCodecs.BigInt UniSwapGraph.Object.Swap
timestamp =
    Object.selectionForField "ScalarCodecs.BigInt" "timestamp" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigInt |> .decoder)


pair :
    SelectionSet decodesTo UniSwapGraph.Object.Pair
    -> SelectionSet decodesTo UniSwapGraph.Object.Swap
pair object_ =
    Object.selectionForCompositeField "pair" [] object_ identity


sender : SelectionSet ScalarCodecs.Bytes UniSwapGraph.Object.Swap
sender =
    Object.selectionForField "ScalarCodecs.Bytes" "sender" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBytes |> .decoder)


amount0In : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.Swap
amount0In =
    Object.selectionForField "ScalarCodecs.BigDecimal" "amount0In" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


amount1In : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.Swap
amount1In =
    Object.selectionForField "ScalarCodecs.BigDecimal" "amount1In" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


amount0Out : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.Swap
amount0Out =
    Object.selectionForField "ScalarCodecs.BigDecimal" "amount0Out" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


amount1Out : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.Swap
amount1Out =
    Object.selectionForField "ScalarCodecs.BigDecimal" "amount1Out" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


to : SelectionSet ScalarCodecs.Bytes UniSwapGraph.Object.Swap
to =
    Object.selectionForField "ScalarCodecs.Bytes" "to" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBytes |> .decoder)


logIndex : SelectionSet (Maybe ScalarCodecs.BigInt) UniSwapGraph.Object.Swap
logIndex =
    Object.selectionForField "(Maybe ScalarCodecs.BigInt)" "logIndex" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigInt |> .decoder |> Decode.nullable)


amountUSD : SelectionSet ScalarCodecs.BigDecimal UniSwapGraph.Object.Swap
amountUSD =
    Object.selectionForField "ScalarCodecs.BigDecimal" "amountUSD" [] (ScalarCodecs.codecs |> UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)
